"""ch02_lie.py -- the Lie bracket as a new direction of motion.

Left: su(2) = R^3 with generators X = -i sx/2, Z = -i sz/2 spanning a plane,
and their bracket [Z, X] = Y leaving it.
Right: the group commutator  e^{-eZ} e^{-eX} e^{eZ} e^{eX}  acting on the Bloch
sphere: four arcs that fail to close by O(e^2) in the direction of the
rotation generated by [Z, X] = Y.  Writes figures/ch02_lie.tex.
"""
import numpy as np
from scipy.linalg import expm
import tikzexport as T
import needham as N

I, X, Y, Z = T.pauli()
EPS = 0.55                                  # angle of each of the four rotations
Xg, Yg, Zg = -0.5j * X, -0.5j * Y, -0.5j * Z


def algebra_panel(V):
    """su(2) as R^3: generators, their span, and the bracket."""
    assert np.allclose(Zg @ Xg - Xg @ Zg, Yg)
    b = []
    corners = [0.9 * np.array(c) for c in [(-1, 0, -1), (1, 0, -1), (1, 0, 1), (-1, 0, 1)]]
    b.append("\\filldraw[wash, draw=ndBlue!40, line width=0.5pt] %s -- cycle;" % " -- ".join(V.pt(c) for c in corners))
    for v in [(1.3, 0, 0), (0, 1.3, 0), (0, 0, 1.3)]:
        b.append("\\draw[faint, ->, >=stealth] %s -- %s;" % (V.pt((0, 0, 0)), V.pt(v)))
    b.append("\\draw[vec, ndBlue] %s -- %s node[below] {$X$};" % (V.pt((0, 0, 0)), V.pt((1, 0, 0))))
    b.append("\\draw[vec, ndBlue] %s -- %s node[left] {$Z$};" % (V.pt((0, 0, 0)), V.pt((0, 0, 1))))
    b.append("\\draw[vec, ndRed] %s -- %s node[below right, text=ndRed] {$[Z,X]=Y$};" % (V.pt((0, 0, 0)), V.pt((0, 1, 0))))
    b.append("\\node[note, anchor=south east, text=ndBlue] at %s {$\\operatorname{span}\\{X,Z\\}$};" % V.pt(corners[3]))
    b.append("\\node[note, anchor=north] (n) at (%.2f,%.2f) {the bracket leaves the plane:\\\\"
             "$\\operatorname{Lie}\\{X,Z\\}=\\liesu[2]$};" % (V.shift[0] + 0.4, V.shift[1] - 1.9))
    b.append("\\node[font=\\small] at (%.2f,%.2f) {(a) the algebra $\\liesu[2]\\cong\\R^3$};"
             % (V.shift[0], V.shift[1] - 3.75))
    return b


def rotation_arc(b, gen, angle, steps=40):
    """Bloch vectors along rho -> e^{angle*gen} rho e^{-angle*gen}."""
    rho = 0.5 * (I + b[0] * X + b[1] * Y + b[2] * Z)
    U = expm(angle / steps * gen)
    pts = []
    for _ in range(steps + 1):
        pts.append(T.bloch_vector(rho))
        rho = U @ rho @ U.conj().T
    return np.array(pts)


def group_panel(V, start):
    """The group commutator loop on the Bloch sphere, started at `start`."""
    b = V.sphere()
    b += V.great_circle([0, 0, 1])
    for v, lab, pos in [((0, 0, 1.25), "z", "above"), ((1.35, 0, 0), "x", "below left"), ((0, 1.3, 0), "y", "right")]:
        b.append("\\draw[faint, ->, >=stealth] %s -- %s node[%s] {$%s$};" % (V.pt((0, 0, 0)), V.pt(v), pos, lab))
    p, arcs = start, []
    for g, a in [(Xg, EPS), (Zg, EPS), (Xg, -EPS), (Zg, -EPS)]:
        arcs.append(rotation_arc(p, g, a))
        p = arcs[-1][-1]
    cx, cy = V.P(np.mean(np.vstack(arcs), axis=0))
    for k, arc in enumerate(arcs, 1):
        b.append(N.polyline([V.P(q) for q in arc], "->, >=stealth, line width=1.3pt, ndBlue"))
        mx, my = V.P(arc[len(arc) // 2])
        d = np.array([mx - cx, my - cy]); d /= np.linalg.norm(d) or 1.0
        b.append("\\node[font=\\scriptsize, text=ndBlue] at (%.3f,%.3f) {%d};" % (mx + 0.22 * d[0], my + 0.22 * d[1], k))
    # leading BCH term: e^{-eZ} e^{-eX} e^{eZ} e^{eX} = e^{eps^2 [Z,X] + O(eps^3)}
    pred = rotation_arc(start, Zg @ Xg - Xg @ Zg, EPS ** 2)
    b.append(N.polyline([V.P(q) for q in pred], "->, >=stealth, line width=1.3pt, ndRed"))
    b.append("\\node[dot] at %s {};" % V.pt(start))
    b.append("\\node[dot, fill=ndBlue] at %s {};" % V.pt(p))
    b.append("\\node[note, anchor=north] (m) at (%.2f,%.2f) {the loop $1,2,3,4$ does not close;\\\\"
             "\\textcolor{ndRed}{its gap $\\approx\\ee^{\\epsilon^2[Z,X]}$}};" % (V.shift[0], V.shift[1] - 2.45))
    b.append("\\draw[pointer] (m.north) to[bend right=25] %s;" % V.pt(pred[len(pred) // 2]))
    b.append("\\node[font=\\small] at (%.2f,%.2f) {(b) the group, acting on the Bloch sphere};"
             % (V.shift[0], V.shift[1] - 3.75))
    return b, np.linalg.norm(p - start), np.linalg.norm(p - pred[-1])


if __name__ == "__main__":
    body = algebra_panel(N.View(az=50, el=20, R=1.8, shift=(0.0, 0.0)))
    start = np.array([0.7, 0.55, 0.45]) / np.linalg.norm([0.7, 0.55, 0.45])
    g, gap, err = group_panel(N.View(az=20, el=20, R=2.3, shift=(6.0, 0.0)), start)
    N.write("ch02_lie", body + g)
    print("written figures/ch02_lie.tex; loop gap %.3f, distance to e^{eps^2[Z,X]} %.3f" % (gap, err))
