"""ch02_group.py -- a Lie group, its Lie algebra, and the exponential map.

The group is G = C^x, the nonzero complex numbers under multiplication, an
honest two-dimensional Lie group.  Writing z = e^{s + i phi} we draw it as the
cylinder (cos phi, sin phi, s): the angle is arg z, the height is log|z|.  Its
Lie algebra is C, the tangent plane at the identity 1.  The one-parameter
subgroup generated by X = a + ib is t -> e^{tX} = e^{ta} e^{itb}, a helix on the
cylinder (a "straight line" of the flat cylinder):
    X = i       the circle U(1), a closed subgroup (e^{2 pi i} = 1),
    X = 1       the positive reals,
    X = 0.25+i  a helix.
Writes figures/ch02_group.tex.
"""
import numpy as np
import needham as N

AZ = 32.0
V = N.View(az=AZ, el=16.0, R=1.7)
SMIN, SMAX = -1.25, 1.85                   # range of heights s = log|z|


def cyl(phi, s):
    """Point of the cylinder for z = exp(s + i phi)."""
    return np.stack([np.cos(phi), np.sin(phi), s], axis=-1)


def on_front(p):
    """Visible iff the outward normal (cos phi, sin phi, 0) faces the viewer."""
    return p[..., 0] * V.d[0] + p[..., 1] * V.d[1] >= 0


def draw_curve(pts, style_front, style_back):
    """Polyline split into visible and hidden runs."""
    out, mask = [], on_front(pts)
    for m, st in [(mask, style_front), (~mask, style_back)]:
        idx = np.where(m)[0]
        if len(idx) == 0 or st is None:
            continue
        for seg in np.split(idx, np.where(np.diff(idx) != 1)[0] + 1):
            if len(seg) > 1:
                out.append(N.polyline([V.P(q) for q in pts[seg]], st))
    return out


def one_param(a, b, t):
    """Points of t -> e^{t(a+ib)} on the cylinder."""
    return cyl(b * t, a * t)


def main():
    b = []
    # --- the cylinder: wash of the visible half, silhouettes, rims
    phi_l, phi_r = np.radians(AZ) + np.pi / 2, np.radians(AZ) - np.pi / 2
    ph = np.linspace(phi_r, phi_l, 90)
    front = [V.P(q) for q in cyl(ph, SMIN * np.ones_like(ph))] + \
            [V.P(q) for q in cyl(ph[::-1], SMAX * np.ones_like(ph))]
    b.append("\\fill[ndSky, fill opacity=0.45] %s -- cycle;" % " -- ".join(N.pt(p) for p in front))
    for phi in (phi_l, phi_r):
        b.append(N.polyline([V.P(cyl(phi, SMIN)), V.P(cyl(phi, SMAX))], "ink"))
    t = np.linspace(0, 2 * np.pi, 200)
    b.append(N.polyline([V.P(q) for q in cyl(t, SMAX * np.ones_like(t))], "ink"))
    b += draw_curve(cyl(t, SMIN * np.ones_like(t)), "ink", "faint, densely dotted")
    # --- one-parameter subgroups
    tt = np.linspace(0, 2 * np.pi, 300)
    b += draw_curve(one_param(0.0, 1.0, tt), "line width=1.5pt, ndBlue", "line width=0.6pt, ndBlue, densely dotted")
    tr = np.linspace(SMIN, SMAX, 50)
    b.append(N.polyline([V.P(q) for q in one_param(1.0, 0.0, tr)], "line width=1.5pt, ndGreen"))
    th = np.linspace(SMIN / 0.25, SMAX / 0.25, 600)    # the whole visible stretch of the helix
    b += draw_curve(one_param(0.25, 1.0, th), "line width=1.5pt, ndRed", "line width=0.6pt, ndRed, densely dotted")
    for k in range(1, 7):                  # equal steps of t on the helix
        p = one_param(0.25, 1.0, np.array([k * 1.0]))[0]
        if on_front(p) and p[2] <= SMAX:
            b.append("\\fill[ndRed] %s circle (1.5pt);" % V.pt(p))
    # --- the tangent plane at 1: the Lie algebra C
    one = cyl(0.0, 0.0)
    e_phi, e_s = np.array([0.0, 1.0, 0.0]), np.array([0.0, 0.0, 1.0])   # d/dphi, d/ds at 1
    w, h = 0.6, 0.55
    corners = [one + a * w * e_phi + c * h * e_s for a, c in [(-1, -1), (1, -1), (1, 1), (-1, 1)]]
    b.append("\\filldraw[fill=ndPaper, fill opacity=0.8, draw=ndInk!70, line width=0.6pt] %s -- cycle;"
             % " -- ".join(V.pt(c) for c in corners))
    L = 0.55
    for vec, col, lab, pos in [(e_phi, "ndBlue", "\\imath", "above"), (e_s, "ndGreen", "1", "left"),
                               ((e_phi + 0.25 * e_s) / np.linalg.norm(e_phi + 0.25 * e_s), "ndRed",
                                "0.25+\\imath", "below right")]:
        b.append("\\draw[vec, %s] %s -- %s node[%s, text=%s, font=\\footnotesize] {$%s$};"
                 % (col, V.pt(one), V.pt(one + L * vec), pos, col, lab))
    b.append("\\node[dot, label={[font=\\footnotesize]below left:$1$}] at %s {};" % V.pt(one))
    b.append("\\node[font=\\footnotesize, anchor=north east] at %s {$\\mathfrak g=T_1G\\cong\\C$};" % V.pt(corners[0]))
    # --- labels and notes
    b.append("\\node[anchor=south] at %s {$G=\\C^\\times$};" % N.pt(V.P(cyl(np.radians(AZ), SMAX)) + np.array([0.0, 0.05])))
    x0 = V.R + 1.0
    b.append("\\node[note, anchor=west] (h) at (%.2f,2.6) {$z=\\ee^{s+\\imath\\varphi}$ drawn at angle $\\varphi$,\\\\"
             "height $s=\\log|z|$};" % x0)
    b.append("\\node[note, anchor=west, text=ndBlue] (c) at (%.2f,1.2) {$\\ee^{t\\imath}$: the circle $\\Un[1]$,\\\\"
             "a closed subgroup};" % x0)
    b.append("\\draw[pointer] (c.west) to[bend right=10] %s;" % V.pt(cyl(np.radians(AZ + 55.0), 0.0)))
    b.append("\\node[note, anchor=west, text=ndRed] (r) at (%.2f,-0.3) {$\\ee^{t(0.25+\\imath)}$: a helix; dots\\\\"
             "at $t=1,2,\\dots$ are equally spaced};" % x0)
    b.append("\\draw[pointer] (r.west) to[bend left=10] %s;" % V.pt(one_param(0.25, 1.0, np.array([np.radians(AZ + 75.0)]))[0]))
    b.append("\\node[note, anchor=west, text=ndGreen!70!black] (g) at (%.2f,-1.7) {$\\ee^{t}$: the positive reals};" % x0)
    b.append("\\draw[pointer] (g.west) to[bend left=15] %s;" % V.pt(one_param(1.0, 0.0, np.array([-0.95]))[0]))
    b.append("\\node[note, anchor=west] at (%.2f,-2.8) {each velocity $X\\in\\mathfrak g$ at $1$ gives\\\\"
             "one curve $t\\mapsto\\ee^{tX}$: a helix};" % x0)
    N.write("ch02_group", b)
    print("written figures/ch02_group.tex")


if __name__ == "__main__":
    main()
