"""tikzexport.py -- tiny helpers to export figures from Python to TikZ/pgfplots.

Course convention (Quantum Optimal Control):
  * every figure is produced by a script  code/chNN_<name>.py  which writes
    figures/chNN_<name>.tex  containing a single  \\begin{tikzpicture} ... \\end{tikzpicture};
  * the chapter includes it with        \\input{figures/chNN_<name>.tex}
  * the same script may be shown (in part) in the notes with \\lstinputlisting.

Only numpy is required (Python >= 3.7).  No tikzplotlib, no matplotlib.
Run a figure script from the course root:  python3 code/ch02_bloch.py
"""
import os
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIGDIR = os.path.join(ROOT, "figures")

# A small, colour-blind-friendly palette (defined as TikZ colours in the header).
PALETTE = [
    ("qocA", "0.00,0.45,0.70"),
    ("qocB", "0.90,0.60,0.00"),
    ("qocC", "0.00,0.62,0.45"),
    ("qocD", "0.80,0.40,0.00"),
    ("qocE", "0.80,0.60,0.70"),
    ("qocF", "0.35,0.70,0.90"),
]


def _colour_defs():
    return "\n".join("\\definecolor{%s}{rgb}{%s}" % (n, rgb) for n, rgb in PALETTE)


def write_tikz(name, body, options=""):
    """Write figures/<name>.tex holding one tikzpicture with the given body."""
    os.makedirs(FIGDIR, exist_ok=True)
    path = os.path.join(FIGDIR, name if name.endswith(".tex") else name + ".tex")
    with open(path, "w") as f:
        f.write("%% Generated by code/%s -- do not edit by hand.\n" % _caller())
        f.write(_colour_defs() + "\n")
        f.write("\\begin{tikzpicture}[%s]\n" % options)
        f.write(body.rstrip() + "\n")
        f.write("\\end{tikzpicture}\n")
    return path


def _caller():
    import inspect
    for fr in inspect.stack()[1:]:
        fn = os.path.basename(fr.filename)
        if fn != os.path.basename(__file__):
            return fn
    return "?"


def _decimate(x, y, max_points=400):
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    if len(x) > max_points:
        idx = np.linspace(0, len(x) - 1, max_points).round().astype(int)
        x, y = x[idx], y[idx]
    return x, y


def coordinates(x, y, max_points=400, fmt="%.5g"):
    """Return a pgfplots 'coordinates {...}' string."""
    x, y = _decimate(x, y, max_points)
    pts = " ".join("(" + fmt % a + "," + fmt % b + ")" for a, b in zip(x, y))
    return "coordinates {%s}" % pts


def pgfplots_axis(series, xlabel="", ylabel="", title="", width="0.85\\linewidth",
                  height="0.5\\linewidth", legend_pos="north east", axis_options="",
                  max_points=400):
    """Return the TikZ body of a pgfplots axis.

    series: list of dicts with keys x, y, label (optional), style (optional TikZ
            options, e.g. "dashed"), and optionally 'const' (bool) for
            piecewise-constant controls (uses 'const plot').
    """
    opts = ["width=%s" % width, "height=%s" % height,
            "xlabel={%s}" % xlabel, "ylabel={%s}" % ylabel,
            "legend pos=%s" % legend_pos, "legend style={font=\\footnotesize}",
            "tick label style={font=\\footnotesize}", "label style={font=\\small}",
            "grid=major", "grid style={gray!20}"]
    if title:
        opts.append("title={%s}" % title)
    if axis_options:
        opts.append(axis_options)
    out = ["\\begin{axis}[%s]" % ", ".join(opts)]
    legend = []
    for i, s in enumerate(series):
        colour = PALETTE[i % len(PALETTE)][0]
        style = ["thick", colour]
        if s.get("style"):
            style.append(s["style"])
        if s.get("const"):
            style.append("const plot")
        out.append("\\addplot[%s] %s;" % (", ".join(style),
                                           coordinates(s["x"], s["y"], max_points)))
        legend.append(s.get("label", ""))
    if any(legend):
        out.append("\\legend{%s}" % ", ".join("{%s}" % l for l in legend))
    out.append("\\end{axis}")
    return "\n".join(out)


def pgfplots_matrix(Z, xlabel="", ylabel="", width="0.6\\linewidth", colorbar=True,
                    axis_options=""):
    """Return the TikZ body of a heat map of matrix Z (rows = y, cols = x)."""
    Z = np.asarray(Z, dtype=float)
    ny, nx = Z.shape
    rows = []
    for j in range(ny):
        for i in range(nx):
            rows.append("%d %d %.5g" % (i, j, Z[j, i]))
    opts = ["width=%s" % width, "height=%s" % width, "xlabel={%s}" % xlabel,
            "ylabel={%s}" % ylabel, "colormap/viridis", "enlargelimits=false",
            "axis on top", "tick label style={font=\\footnotesize}"]
    if colorbar:
        opts.append("colorbar")
    if axis_options:
        opts.append(axis_options)
    body = ["\\begin{axis}[%s]" % ", ".join(opts),
            "\\addplot[matrix plot*, point meta=explicit, mesh/cols=%d] table[meta=z] {" % nx,
            "x y z"] + rows + ["};", "\\end{axis}"]
    return "\n".join(body)


def bloch_sphere(trajectories=(), radius=2.5, labels=True, points=()):
    """Return a TikZ body drawing a Bloch sphere (orthographic-ish projection)
    with optional trajectories: list of (N,3) arrays of Bloch vectors, and
    optional labelled points: list of (r, text)."""
    # projection of (x, y, z) onto the page: simple oblique projection
    def P(v):
        x, y, z = v
        return (radius * (0.9 * x - 0.45 * y), radius * (z - 0.2 * y))

    R = radius
    out = []
    out.append("\\draw[thick] (0,0) circle (%.3f);" % R)
    out.append("\\draw[dashed] (0,0) ellipse (%.3f and %.3f);" % (R, 0.35 * R))
    out.append("\\draw[->] (0,0) -- (0,%.3f) node[above] {%s};" % (R * 1.25, "$\\ket{0}$" if labels else ""))
    out.append("\\draw[->] (0,0) -- (0,%.3f) node[below] {%s};" % (-R * 1.25, "$\\ket{1}$" if labels else ""))
    px, py = P((1.25, 0, 0))
    out.append("\\draw[->] (0,0) -- (%.3f,%.3f) node[right] {%s};" % (px, py, "$x$" if labels else ""))
    px, py = P((0, 1.25, 0))
    out.append("\\draw[->] (0,0) -- (%.3f,%.3f) node[above left] {%s};" % (px, py, "$y$" if labels else ""))
    for i, traj in enumerate(trajectories):
        colour = PALETTE[i % len(PALETTE)][0]
        traj = np.asarray(traj, dtype=float)
        if len(traj) > 300:
            traj = traj[np.linspace(0, len(traj) - 1, 300).round().astype(int)]
        pts = " -- ".join("(%.3f,%.3f)" % P(v) for v in traj)
        out.append("\\draw[very thick, %s] %s;" % (colour, pts))
        px, py = P(traj[-1])
        out.append("\\fill[%s] (%.3f,%.3f) circle (2pt);" % (colour, px, py))
    for v, text in points:
        px, py = P(v)
        out.append("\\fill (%.3f,%.3f) circle (1.5pt) node[above right, font=\\small] {%s};" % (px, py, text))
    return "\n".join(out)


def pauli():
    """Return (I, X, Y, Z) as 2x2 complex numpy arrays."""
    I = np.eye(2, dtype=complex)
    X = np.array([[0, 1], [1, 0]], dtype=complex)
    Y = np.array([[0, -1j], [1j, 0]], dtype=complex)
    Z = np.array([[1, 0], [0, -1]], dtype=complex)
    return I, X, Y, Z


def bloch_vector(rho):
    """Bloch vector of a 2x2 density matrix."""
    _, X, Y, Z = pauli()
    return np.real(np.array([np.trace(rho @ X), np.trace(rho @ Y), np.trace(rho @ Z)]))
